### ISSUE TITLE
manifest v3 support?

### ISSUE THREAD

**Issue by alexcc4** [henices/Chrome-proxy-helper#32]

**Comment by Kazintsev** [comment]
Hello!

What do you think regarding [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1135492)?


Best regards,
Nick

**Comment by henices** [comment]
> Hello!
> 
> What do you think regarding [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1135492)?
> 
> Best regards, Nick

Sadly,unless Google give us a solution,I'm afraid we can't do anything more.

**Comment by humorwang** [comment]
google seems to have given a solution [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1135492)

**Comment by henices** [comment]
> google seems to have given a solution [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1135492)

Good news !  I will look into it.  Thanks a lot.

**Comment by alexcc4** [comment]
Any update for this?

**Comment by alexcc4** [comment]
I saw a link recently. Is it of any reference?
- [chrome.webRequest.onAuthRequired](https://stackoverflow.com/questions/76969107/api-chrome-webrequest-onauthrequired-window-in-browser-when-authorizing-proxy-o)
- [adguard](https://adguard-vpn.com/en/blog/mv3-browser-extension.html)

**Comment by leor-gh** [comment]
Chrome adds the new "webRequestAuthProvider" permission the Proxy Authentication is now supported.

I made absolutely minimum changes to migrate the extension to MV3 and it is about 80 lines of JS code. All supported features seem to be working as expected. I have not tested the chinaList bypass since it is commented out in the existing released code.

Should I create a PR to resolve this issue?

**Comment by henices** [comment]
> Chrome adds the new "webRequestAuthProvider" permission and Proxy Authentication is now supported.
> 
> I made absolutely minimum changes to migrate the extension to MV3 and it is about 80 lines of JS code. All supported features seem to be working as expected. I have not tested the chinaList bypass since it is commented out in the existing released code.
> 
> Should I create a PR to resolve this issue?

Thanks a lot. Contributions are always welcome.  I'll review the code and merge it.

Thanks again. 😄️

**Comment by leor-gh** [comment]
PR created.

As said, this change is bare minimum changes to get it working in MV3. There are a number of enhancement to do after the code migration.

**Comment by leor-gh** [comment]
I mentioned in my code commit that it didn't take care of data migration from existing MV2 installation to MV3. The only relevant data that needs migrating is the proxy authorization credentials in my persistent data storage design.

I found a way to do this by using an one-off offscreen document in the onInstalled handler. This is my POC approach that works:

In the onInstalled listener, if the reason is update and chrome.storage is not initialized, this is the situation of the first run after migrating from MV2.
  -  Install a new message handler to process a "close" message
  -  create an offscreen document with access to LOCAL_STORAGE
  -  in the offscreen document JS code, if there is existing localStorage (it should always be) and a non-empty credential, then send the "authUpdate" message to the service worker with the credential
  -  the offscreen document sends the "close" message to the service worker
  -  the service worker closes the offscreen document

Happy to share the code. Just let me know.

**Comment by henices** [comment]
I'm not familiar with the communication mechanism of Chrome extension service workers, but I think your design works.

Feel free to make a pull request. Thanks a lot for your contribution. 🙂

**Comment by leor-gh** [comment]
Yeah me neither. Just started to learn about browser extensions Tuesday. I'll do some clean up and create a PR this weekend.
